### ISSUE TITLE
As a ui-developer, I want to be able to show two different google region maps on the same page so that I can visualize two different things

### ISSUE THREAD

**Issue by nicklondhe** [ibm-watson-data-lab/pixiedust#396] opened 2017-06-30 22:24 UTC
As a ui-developer, I want to be able to show two different google region maps on the same page so that I can visualize two different things

### Expected behavior
1. Design a pixie dust app with two different google region maps
2. Bind two different entities to each widget
3. On loading the page, both visualizations show up

### Actual behavior
1. Both widgets seem to target the same div, ie. the second widget consistently overwrites the first one.

### Steps to reproduce the behavior
See above.

Sample code fragment:
```
<li role="presentation"><a data-toggle="tab" data-pt-cat="socialissues" pixiedust href="#pane-gt-si-{{prefix}}">Social Issues
                    <target pd_target="pane-si2{{prefix}}" pd_entity="corrrisk" pd_options="handlerId=mapView;keyFields=Code;valueFields=ITM;rendererId=google;aggregation=SUM;mapRegion=CO;mapColorAxis=#FF0000,#FFFF00;noChartCache=true;"/>   
                    <target pd_target="pane-si3{{prefix}}" pd_entity="womhom" pd_options="handlerId=mapView;keyFields=Dep Code;valueFields=log dpc;rendererId=google;aggregation=SUM;mapRegion=CO;mapColorAxis=#00FF00,#FF0000;noChartCache=true;"/> 
                </a></li>
....
<div class="col-md-6">
                  <div class="row">
                    <div class="col-sm-12">
                      <div class="title-div">Corruption Risk</div>
                      <div id="pane-si2{{prefix}}" class="vis-wrapper vis-wrapper-gt5"></div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-sm-12">
                      <div class="title-div">Women Homicides per Capita</div>
                      <div id="pane-si3{{prefix}}" class="vis-wrapper vis-wrapper-gt6"></div>
                    </div>
                  </div>
                </div>
```

Only the second map shows up, loaded within the first div (si2)

**Comment by vabarbosa** [comment] 2017-07-07 16:07
the problem is the map DIV container ID is no longer unique when placing multiple maps in the same pixieapp. issue has been resolved in commit https://github.com/ibm-watson-data-lab/pixiedust/commit/6be942436c3b157ad45a3e75232536d85a1c75f2 (PR #401)

**Closed** 2017-07-16 15:22 UTC
