### ISSUE TITLE
DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future

### ISSUE THREAD

**Issue by rolweber** [ibm-watson-data-lab/pixiedust#448] opened 2017-09-18 11:16 UTC
Importing pixiedust 1.0.11 yields the following warning:
```
DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  NP_EPOCH = np.datetime64('1970-01-01T00:00:00Z')
```
Observed on DSX with both Python 2.7 and Python 3.5. Origins of the warning:

Python 2.7: `/usr/local/src/bluemix_jupyter_bundle.v61/notebook/lib/python2.7/site-packages/bokeh/core/json_encoder.py:52`
Python 3.5: `/usr/local/src/conda3_runtime.v17/4.1.1/lib/python3.5/site-packages/bokeh/core/json_encoder.py:52`

Bokeh version is 0.12.5 in both cases.

### Expected behavior
pixiedust imports without warning

### Actual behavior
pixiedust produces a warning on import

### Steps to reproduce the behavior
```
import pixiedust
```

**Comment by DTAIEB** [comment] 2017-09-18 13:21
@rolweber This bokeh issue was fixed in 0.12.6: https://github.com/bokeh/bokeh/pull/6192
I suggest we upgrade to this version on DSX.

**Closed by DTAIEB** 2017-09-18 13:21 UTC

**Comment by rolweber** [comment] 2017-09-18 13:32
Ack. 0.12.9 is current, I'll jump to that.

**Comment by rolweber** [comment] 2017-09-18 13:46
How about requiring bokeh 0.12.6 or later in pixiedust?

**Comment by DTAIEB** [comment] 2017-09-18 14:13
Can't add Bokeh as a required dependency in setup.py because by design it is an optional renderer. If not installed, PixieDust will simply not show it in the renderer dropdown. If installed, we could dynamically check its version before allowing the renderer to proceed, but I think it's overkill since it's only a warning.
